-- CreateEnum
CREATE TYPE "CustomerRejectReason" AS ENUM ('OUT_OF_STOCK', 'OUTSIDE_DELIVERY_HOURS', 'TOO_BUSY', 'OUT_OF_AREA', 'OTHER');

-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "marketingOptIn" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "privacyAcceptedAt" TIMESTAMP(3),
ADD COLUMN     "privacyVersion" TEXT;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "clientIpHash" TEXT,
ADD COLUMN     "customerRejectReason" "CustomerRejectReason",
ADD COLUMN     "customerRejectText" TEXT,
ADD COLUMN     "pixReportedAt" TIMESTAMP(3),
ADD COLUMN     "trackingToken" TEXT;

-- Existing orders get a random 128-bit token too (new ones are generated by the API).
UPDATE "Order" SET "trackingToken" = md5(random()::text || clock_timestamp()::text || "id");
ALTER TABLE "Order" ALTER COLUMN "trackingToken" SET NOT NULL;

-- AlterTable
ALTER TABLE "Store" ADD COLUMN     "brandColor" TEXT,
ADD COLUMN     "digitalLimitIpHour" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "digitalLimitPhoneDay" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "digitalLimitPhoneOpen" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "digitalLimitStorePending" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "menuCoverKey" TEXT,
ADD COLUMN     "menuDescription" TEXT,
ADD COLUMN     "privacyNotice" TEXT;

-- CreateTable
CREATE TABLE "BlockedPhone" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL DEFAULT current_setting('app.tenant_id'::text),
    "phone" TEXT NOT NULL,
    "reason" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BlockedPhone_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DeliveryQuoteMiss" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL DEFAULT current_setting('app.tenant_id'::text),
    "neighborhood" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DeliveryQuoteMiss_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "BlockedPhone_tenantId_phone_key" ON "BlockedPhone"("tenantId", "phone");

-- CreateIndex
CREATE INDEX "DeliveryQuoteMiss_tenantId_createdAt_idx" ON "DeliveryQuoteMiss"("tenantId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "Order_trackingToken_key" ON "Order"("trackingToken");

-- CreateIndex
CREATE INDEX "Order_tenantId_customerPhone_createdAt_idx" ON "Order"("tenantId", "customerPhone", "createdAt");

-- CreateIndex
CREATE INDEX "Order_tenantId_clientIpHash_createdAt_idx" ON "Order"("tenantId", "clientIpHash", "createdAt");



-- Values (Prisma does not express CHECK constraints; they are not tracked for drift).
ALTER TABLE "Store" ADD CONSTRAINT "Store_digital_menu_check" CHECK (
  ("brandColor" IS NULL OR "brandColor" ~ '^#[0-9a-fA-F]{6}$')
  AND "digitalLimitPhoneOpen" > 0 AND "digitalLimitPhoneDay" > 0
  AND "digitalLimitIpHour" > 0 AND "digitalLimitStorePending" > 0
);
